# Site settings
title: "Yashvardhan Asthana Portfolio"
description: "A personal portfolio website"
url: "https://yourusername.github.io"
baseurl: ""

# Build settings
theme: jekyll-theme-primer
markdown: kramdown

# Exclude from processing
exclude:
  - README.md

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
